name: Bug Report
description: File a bug report.
blank_issues_enabled: false
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: Expected Behaviour
    attributes:
      label: Expected Behaviour
      description: What did you expect to happen?
      placeholder: 
    validations:
      required: true